import { RopeConfig } from './rope-physics.models';

export const DESIGN_W = 1376;
export const DESIGN_H = 768;

export const ROPE_COLOR_LANTERN = 'rgba(125, 90, 52, 0.85)';
export const ROPE_COLOR_STAR = 'rgba(100, 80, 58, 0.82)';
export const ROPE_GLOW_LANTERN = 'rgba(251, 191, 36, 0.15)';
export const ROPE_GLOW_STAR = 'rgba(251, 191, 36, 0.10)';

/**
 * Measured configurations for all 13 hanging items.
 * Anchor coordinates match the sanctuary artwork coordinate system.
 * Rope lengths match the exact height of the clipped static rope.
 */
export const DEFAULT_ROPE_CONFIGS: RopeConfig[] = [
  // ---- Hanging Lanterns (6 items) ----
  {
    id: 'lantern-hanging-left-top',
    anchorX: 152,
    anchorY: 0,
    length: 22,
    bodyWidth: 39,
    bodyHeight: 53,
    segments: 5,
    thickness: 1.4,
    color: ROPE_COLOR_LANTERN,
    glowColor: ROPE_GLOW_LANTERN,
    influenceRadius: 40,
    reactivity: 0.42,
    gravityScale: 1.0,
    damping: 0.976,
  },
  {
    id: 'lantern-hanging-left-mid',
    anchorX: 156,
    anchorY: 302,
    length: 46,
    bodyWidth: 39,
    bodyHeight: 47,
    segments: 6,
    thickness: 1.4,
    color: ROPE_COLOR_LANTERN,
    glowColor: ROPE_GLOW_LANTERN,
    influenceRadius: 42,
    reactivity: 0.40,
    gravityScale: 1.0,
    damping: 0.977,
  },
  {
    id: 'lantern-hanging-center-left',
    anchorX: 499,
    anchorY: 354,
    length: 25,
    bodyWidth: 17,
    bodyHeight: 26,
    segments: 5,
    thickness: 1.3,
    color: ROPE_COLOR_LANTERN,
    glowColor: ROPE_GLOW_LANTERN,
    influenceRadius: 38,
    reactivity: 0.42,
    gravityScale: 1.0,
    damping: 0.975,
  },
  {
    id: 'lantern-hanging-center-right',
    anchorX: 870,
    anchorY: 400,
    length: 12,
    bodyWidth: 12,
    bodyHeight: 18,
    segments: 3,
    thickness: 1.3,
    color: ROPE_COLOR_LANTERN,
    glowColor: ROPE_GLOW_LANTERN,
    influenceRadius: 38,
    reactivity: 0.40,
    gravityScale: 1.0,
    damping: 0.975,
  },
  {
    id: 'lantern-hanging-right-mid',
    anchorX: 1220,
    anchorY: 296,
    length: 42,
    bodyWidth: 40,
    bodyHeight: 44,
    segments: 6,
    thickness: 1.4,
    color: ROPE_COLOR_LANTERN,
    glowColor: ROPE_GLOW_LANTERN,
    influenceRadius: 42,
    reactivity: 0.40,
    gravityScale: 1.0,
    damping: 0.977,
  },
  {
    id: 'lantern-hanging-right-top',
    anchorX: 1214,
    anchorY: 38,
    length: 46,
    bodyWidth: 33,
    bodyHeight: 42,
    segments: 6,
    thickness: 1.3,
    color: ROPE_COLOR_LANTERN,
    glowColor: ROPE_GLOW_LANTERN,
    influenceRadius: 38,
    reactivity: 0.40,
    gravityScale: 1.0,
    damping: 0.976,
  },

  // ---- Hanging Star Lanterns (7 items) ----
  {
    id: 'star-left-1',
    anchorX: 112,
    anchorY: 619,
    length: 70,
    bodyWidth: 54,
    bodyHeight: 31,
    segments: 9,
    thickness: 1.1,
    color: ROPE_COLOR_STAR,
    glowColor: ROPE_GLOW_STAR,
    influenceRadius: 40,
    reactivity: 0.46,
    gravityScale: 1.0,
    damping: 0.980,
  },
  {
    id: 'star-left-2',
    anchorX: 220,
    anchorY: 578,
    length: 49,
    bodyWidth: 46,
    bodyHeight: 18,
    segments: 7,
    thickness: 1.1,
    color: ROPE_COLOR_STAR,
    glowColor: ROPE_GLOW_STAR,
    influenceRadius: 38,
    reactivity: 0.45,
    gravityScale: 1.0,
    damping: 0.978,
  },
  {
    id: 'star-center',
    anchorX: 505,
    anchorY: 477,
    length: 33,
    bodyWidth: 46,
    bodyHeight: 19,
    segments: 6,
    thickness: 1.1,
    color: ROPE_COLOR_STAR,
    glowColor: ROPE_GLOW_STAR,
    influenceRadius: 38,
    reactivity: 0.45,
    gravityScale: 1.0,
    damping: 0.977,
  },
  {
    id: 'star-right-1',
    anchorX: 1175,
    anchorY: 558,
    length: 49,
    bodyWidth: 50,
    bodyHeight: 25,
    segments: 7,
    thickness: 1.1,
    color: ROPE_COLOR_STAR,
    glowColor: ROPE_GLOW_STAR,
    influenceRadius: 38,
    reactivity: 0.45,
    gravityScale: 1.0,
    damping: 0.978,
  },
  {
    id: 'star-right-2',
    anchorX: 1205,
    anchorY: 553,
    length: 129,
    bodyWidth: 58,
    bodyHeight: 34,
    segments: 12,
    thickness: 1.1,
    color: ROPE_COLOR_STAR,
    glowColor: ROPE_GLOW_STAR,
    influenceRadius: 42,
    reactivity: 0.48,
    gravityScale: 1.0,
    damping: 0.981,
  },
  {
    id: 'star-right-3',
    anchorX: 1239,
    anchorY: 604,
    length: 49,
    bodyWidth: 42,
    bodyHeight: 18,
    segments: 7,
    thickness: 1.1,
    color: ROPE_COLOR_STAR,
    glowColor: ROPE_GLOW_STAR,
    influenceRadius: 36,
    reactivity: 0.44,
    gravityScale: 1.0,
    damping: 0.977,
  },
  {
    id: 'star-right-4',
    anchorX: 1276,
    anchorY: 668,
    length: 38,
    bodyWidth: 40,
    bodyHeight: 18,
    segments: 5,
    thickness: 1.1,
    color: ROPE_COLOR_STAR,
    glowColor: ROPE_GLOW_STAR,
    influenceRadius: 34,
    reactivity: 0.42,
    gravityScale: 1.0,
    damping: 0.975,
  },
];
